<b>Modeling situation</b> <a class="right" href="https://hyperskill.org/learn/step/6274">Open on Hyperskill</a><br/><br/><html>
 <head></head>
 <body>
  <p>Your program will have access to the <code>exception_test()</code> function, which can throw exceptions.</p> 
  <p>You need to write code that runs this function, then catches <code>ArithmeticError</code>, <code>AssertionError</code>&nbsp;,&nbsp;<code>ZeroDivisionError</code>&nbsp;exceptions and prints the name of the caught exception.</p> 
  <p>An example solution that you should send for review:</p> 
  <pre><code class="language-python">try:
    exception_test()
except Exception:
    print("Exception")
except BaseException:
    print("BaseException")</code></pre> 
  <p>[HINT]Don't forget about the hierarchy of exceptions. The key to this task is to choose the correct order of except clauses.[/HINT]</p>
 </body>
</html><br><br><font color="gray">Memory limit: 256 Mb</font><br><font color="gray">Time limit: 2s</font><br><br><br/><a href="https://hyperskill.org/learn/step/6270">Show topic summary</a>